title: MagTek Docs
description: MagTek Docs
theme: just-the-docs

url: https://MagTek-PaulDeignan.github.io/MagTekDocs

logo: "/assets/images/magtek_logo.png"
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: light

just_the_docs:
  custom_css: /assets/css/custom.css

jekyll_admin:
  hidden_links:
    - posts
    - configuration
  homepage: "pages"
